/// Self-contained Studio translations. Store metadata and process logs are never translated here.
const studioLocalizationScript = r'''
'use strict';
const uiMessages = {
  "{count} hedef dilde {fields} alan boş. Çeviri görevi yalnızca boş alanları doldurur.": "Target languages: {count}. Missing fields: {fields}. The task fills only empty fields.",
  "{count} hedef dil · {fields} alan eksik. Görev bunları dolduracak.": "Target languages: {count} · Missing fields: {fields}. The task will fill them.",
  "Arayüz dili bu oturumda değişti; kalıcı tercih kaydedilemedi.": "Interface language changed for this session, but the preference could not be saved.",
  "Torchinlane Studio": "Torchinlane Studio",
  "🔥 Torchinlane Studio": "🔥 Torchinlane Studio",
  "Kurulumu kontrol et, metinleri hazırla, mağazaya gönder.": "Check setup, prepare content, upload to your stores.",
  "Flutter projesi": "Flutter project",
  "Başlangıç": "Overview",
  "1. Kurulum": "1. Setup",
  "2. Metinler": "2. Texts",
  "3. Çeviri": "3. Translation",
  "4. Görseller": "4. Images",
  "5. Gönder": "5. Upload",
  "Proje kontrol ediliyor…": "Checking the project…",
  "Nereden devam etmelisin?": "Where should you continue?",
  "Mevcut ayar ve dosyalar kontrol edilir. Tamamlanan işleri tekrar yapmana gerek yok. Yalnızca kullanacağın mağazayı seç.": "Existing settings and files are checked. Completed steps do not need repeating. Select only the stores you will use.",
  "Hedef mağaza": "Target stores",
  "App Store ve Google Play": "App Store and Google Play",
  "Yalnızca Google Play": "Google Play only",
  "Yalnızca App Store": "App Store only",
  "Dosyaları tekrar kontrol et": "Check files again",
  "Önerilen adıma git": "Go to the recommended step",
  "Metin hazırlamak ve çeviri görevi oluşturmak için anahtar veya API bağlantısı gerekmez. Mağaza bağlantısı yalnızca yükleme için; imzalama ise uygulama build'i için gerekir.": "Preparing content and translation tasks needs no key or API connection. Store access is needed for uploads; signing is needed for app builds.",
  "Mağaza": "Store",
  "App Store": "App Store",
  "Google Play": "Google Play",
  "Düzenlenen dil": "Language being edited",
  "2. Önce kaynak metinlerini yaz": "2. Write your source texts first",
  "Uygulama adını, açıklamasını ve sürüm notlarını bildiğin dilde yaz. Hazır metinler varsa değiştirmene gerek yok. Boş alanlar mevcut mağaza metinlerini silmez.": "Write the app name, description and release notes in a language you know. Keep existing texts if they are ready. Empty fields do not delete existing store text.",
  "Kaynak dili aç": "Open source language",
  "Diğer mağazadan kaynak metni al": "Reuse source text from the other store",
  "Metinleri kaydet": "Save texts",
  "Kaydedilen metinleri kontrol et": "Check saved texts",
  "← Kurulum": "← Setup",
  "Çeviriye geç →": "Continue to translation →",
  "3. Diğer dilleri doldur": "3. Fill the other languages",
  "Aşağıdan istediğin dilleri ekle. Zaten ekli dilleri tekrar seçmene gerek yok.": "Add your target languages below. You do not need to add languages that already exist.",
  "Çeviri görevini hazırla": "Prepare translation task",
  "ve": "and",
  "Görevi kopyala": "Copy task",
  "düğmelerine bas.": "buttons.",
  "Flutter projen içinde çalışan Claude Code veya Codex'e yapıştır. Ajan dosyaları doldursun.": "Paste into Claude Code or Codex working in your Flutter project. Let the agent fill the files.",
  "Buraya dön ve": "Return here and click",
  "Sonuçları yükle ve kontrol et": "Reload and check results",
  "düğmesine bas.": ".",
  "Ayrı çeviri API anahtarı gerekmez. Apple/Google dil kodları ve metin sınırları göreve otomatik eklenir. Dolu çeviriler korunur.": "No separate translation API key is needed. Apple/Google locale codes and field limits are included in the task. Existing translations are preserved.",
  "Eklenecek dil": "Language to add",
  "Dili ekle": "Add language",
  "Hangi dilden çevrilecek?": "Translate from which language?",
  "İleri seçenekler": "Advanced options",
  "Desteklenen bütün dilleri ekle": "Add all supported languages",
  "Dolu çevirileri de yeniden yaz": "Rewrite existing translations too",
  "İstersen doğrudan Anthropic API kullanabilirsin. Bu seçenek API anahtarı gerektirir ve ayrıca ücretlendirilebilir.": "You may use the Anthropic API directly. This optional method requires an API key and may incur separate charges.",
  "İsteğe bağlı API ile çevir": "Translate via optional API",
  "Görevi ajanına yapıştır": "Paste the task into your agent",
  "Claude Code/Codex bu Flutter projesinde açık olmalı. İşlem tamamlandığında aşağıdaki sonuç kontrolüne geç.": "Claude Code/Codex must be open in this Flutter project. When it finishes, check the results below.",
  "Hazır çeviri görevi": "Prepared translation task",
  "← Metinler": "← Texts",
  "Görsellere geç →": "Continue to images →",
  "4. Görselleri ekle — gerekiyorsa": "4. Add images — if needed",
  "Mağazadaki görsellerin zaten uygunsa bu adımı geçebilirsin. Yeni görseller yüklemek için yukarıdan dil, aşağıdan cihaz/görsel türü seç. PNG/JPEG dosyalarını ekle; boyutları otomatik kontrol edilir.": "Skip this step if your store images are already suitable. To upload new images, select the language above and the device/asset type below. Add PNG/JPEG files; dimensions are checked automatically.",
  "Cihaz veya görsel türü": "Device or asset type",
  "Görsel dosyaları": "Image files",
  "Görseldeki yazıları bu araç çevirmiyor. Her dil için hazır görsel ekle. Oklarla yükleme sırasını değiştirebilirsin.": "This tool does not translate text inside images. Add ready-made assets for each language. Use the arrows to change upload order.",
  "← Çeviri": "← Translation",
  "Göndermeye geç →": "Continue to upload →",
  "5. Hazır içeriği mağazaya gönder": "5. Upload ready content to your stores",
  "Bu bölüm metin/görselleri gönderir; uygulama build'i oluşturmaz. Önce yükleme planını kontrol et, sonra gönder. Apple incelemesi veya Google production dağıtımı başlatılmaz.": "This section uploads texts/images without building the app. Check the upload plan first, then upload. It does not submit an Apple review or start a Google production rollout.",
  "İki mağaza": "Both stores",
  "Ne göndereceksin?": "What will you upload?",
  "Uygulama metinleri": "App metadata",
  "Görseller": "Images",
  "Sürüm notları": "Release notes",
  "Metinler, görseller ve notlar": "Texts, images and notes",
  "Google sürüm notları için mağazada zaten bulunan build numarasını ve kanalını seç. Yeni build göndermek istiyorsan aşağıdaki uygulama build bölümünü kullan.": "Google release notes need a build number and track already present in the store. To upload a new build, use the app build section below.",
  "Google build numarası (version code)": "Google build number (version code)",
  "Google yayın kanalı": "Google release track",
  "Dahili test (internal)": "Internal testing (internal)",
  "Kapalı test (alpha)": "Closed testing (alpha)",
  "Açık test (beta)": "Open testing (beta)",
  "Production": "Production",
  "İleri yükleme seçenekleri": "Advanced upload options",
  "Apple düzenlenecek sürüm (isteğe bağlı)": "Apple editable version (optional)",
  "Gönderilen Apple dillerinin mevcut ekran görüntülerini değiştir": "Replace existing Apple screenshots in supplied locales",
  "Bu seçenek ilgili dillerdeki bütün Apple cihaz setlerini temizleyebilir. Google yalnızca gönderilen görsel gruplarını değiştirir.": "This may clear all Apple device screenshot sets in the supplied locales. Google replaces only the supplied image groups.",
  "Fastlane dosyalarını dışa aktar": "Export Fastlane files",
  "Mağazadaki metinlerle karşılaştır": "Compare with store texts",
  "Mağaza metinlerini yedekleyerek içe al": "Import store texts with backups",
  "1. Yükleme planını kontrol et": "1. Check upload plan",
  "2. İçeriği gönder": "2. Upload content",
  "Yeni uygulama build'i göndereceğim": "I want to upload a new app build",
  "Yalnızca yeni AAB/IPA göndereceksen bu bölüm gerekir. Mağaza metinleri için imzalama kurulumu yapmana gerek yok.": "Use this section only for a new AAB/IPA. Store metadata uploads do not require signing setup.",
  "Build hedefi": "Build destination",
  "TestFlight / Google dahili test taslağı": "TestFlight / Google internal testing draft",
  "App Store / Google production taslağı": "App Store / Google production draft",
  "Zaten oluşturulmuş build'i gönder": "Upload an existing build",
  "Mağaza içeriklerini de gönder": "Include store content",
  "Build planını gör": "Preview build plan",
  "Build oluştur ve gönder": "Build and upload",
  "Google build'leri taslak kalır. Production dağıtımı için CLI release-status seçeneğini kullan. Apple inceleme gönderimi ayrıdır.": "Google releases stay drafts. Use the CLI release-status option for a production rollout. Apple review submission is separate.",
  "← Görseller": "← Images",
  "Durum ekranına dön": "Return to overview",
  "1. Proje kurulumu": "1. Project setup",
  "Mevcut değerler aşağıda görünür. Hazırsa yeniden kaydetmen gerekmez. İçerik hazırlamak için uygulama adı ve kaynak dil yeterlidir; hesap bilgilerini göndermeden önce tamamlayabilirsin.": "Existing values are shown below. Do not save them again if they are ready. App name and source language are enough to prepare content; complete account details before uploading.",
  "Ayarları kaydet": "Save settings",
  "Eksik/güncel olmayan dosyaları tamamla": "Complete missing/outdated helper files",
  "App Store bağlantısı": "App Store connection",
  "Apple anahtarı ekle / değiştir": "Add / change Apple key",
  "App Store Connect API anahtarları": "App Store Connect API keys",
  "sayfasını aç.": "page.",
  "Team API key oluşturup .p8 dosyasını indir. Mevcut anahtarın varsa yenisini oluşturma.": "Create a team API key and download the .p8 file. If you have a key already, do not create a new one.",
  "Key ID / Issuer ID'yi proje ayarlarına yazıp kaydet; dosyayı aşağıdan seç.": "Enter and save the Key ID / Issuer ID in project settings, then select the file below.",
  "Apple .p8 dosyası": "Apple .p8 file",
  "Birden fazla projede kullanacağım": "Use across multiple projects",
  "Profil adı (isteğe bağlı)": "Profile name (optional)",
  "Anahtarı bu projeye ekle": "Add key to this project",
  "Mağaza erişimini kontrol et": "Check store access",
  "Google Play bağlantısı": "Google Play connection",
  "Google kimlik dosyası ekle / değiştir": "Add / change Google credential file",
  "Google Cloud": "Google Cloud",
  "üzerinden service account oluştur; Google Play Developer API'yi aç.": "to create a service account; enable the Google Play Developer API.",
  "Play Console": "Play Console",
  "'da service account e-postasına uygulama erişimi ver.": "to grant the service account email access to the app.",
  "JSON dosyasını aşağıdan seç. Mevcut geçerli dosyan varsa bunları tekrar yapma.": "Select the JSON file below. Skip these steps if you already have a valid file.",
  "Google JSON dosyası": "Google JSON file",
  "Dosyayı bu projeye ekle": "Add file to this project",
  "Yeni Google uygulamasının ilk build'i Play Console'dan yüklenmelidir. WIF/OAuth ve yardımcı CLI komutları doc/automation.md rehberinde açıklanır.": "New Google apps need their first build uploaded through Play Console. WIF/OAuth and helper CLI commands are explained in doc/automation.md.",
  "Build araçları — yalnızca build/yükleme için": "Build tools — only for builds/uploads",
  "Henüz kontrol edilmedi. Metin ve çeviri hazırlamak için bu adımı geçebilirsin.": "Not checked yet. You can skip this step when preparing texts and translations.",
  "Araçları kontrol et": "Check tools",
  "Fastlane / CocoaPods eksiklerini düzelt": "Repair Fastlane / CocoaPods",
  "Uygulama imzalama kontrolü": "App signing check",
  "Dosyaların bulunması tek başına imzalamanın çalıştığını kanıtlamaz. Başarılı mevcut release build'in varsa yeni anahtar üretme. Android için mevcut upload keystore'unu kullan; iOS için mevcut Xcode ayarlarını koru veya Fastlane match ile eşitle.": "Finding files does not prove signing works. If an existing release build succeeds, do not generate a new key. Use your existing Android upload keystore; preserve your Xcode setup or sync with Fastlane match on iOS.",
  "← Durum ekranı": "← Overview",
  "Metinlere geç →": "Continue to texts →",
  "İşlem ayrıntıları ·": "Operation details ·",
  "Beklemede": "Idle",
  "Dosyalar bilgisayarında kalır. Çeviri görevini paylaştığın ajan metinleri görür. Mağazaya gönderme işlemi Apple/Google'a bağlanır.": "Files stay on your computer. The agent receiving your translation task sees its texts. Store uploads connect to Apple/Google.",
  "Örnek: 42": "Example: 42",
  "Örnek: 1.2.0": "Example: 1.2.0",
  "company-apple": "company-apple",
  "company-google": "company-google",
  "Uygulama adı": "App name",
  "Alt başlık": "Subtitle",
  "Uzun açıklama": "Full description",
  "Tanıtım metni": "Promotional text",
  "Destek bağlantısı": "Support URL",
  "Tanıtım sitesi": "Marketing URL",
  "Gizlilik politikası bağlantısı": "Privacy policy URL",
  "Bu sürümde neler değişti?": "What changed in this release?",
  "Kısa açıklama": "Short description",
  "YouTube video bağlantısı": "YouTube video URL",
  "Bu mağaza için henüz dil dosyası yok. Kaynak dili aç düğmesiyle oluşturabilirsin.": "No locale files exist for this store yet. Use Open source language to create one.",
  "İleri metin alanları ve bağlantılar": "Advanced text fields and URLs",
  "←": "←",
  "→": "→",
  "Dosyayı kaldır": "Remove file",
  "Mağaza değiştirmeden önce metinleri kaydet.": "Save texts before switching stores.",
  "Dil değiştirmeden önce metinleri kaydet.": "Save texts before switching languages.",
  "Metinler kaydedildi. İstersen şimdi çeviri adımına geç.": "Texts saved. You can continue to translation.",
  "Önce metinleri kaydet.": "Save texts first.",
  "Kaydedilen içerik kontrol edildi; sorun bulunmadı.": "Saved content was checked; no issues found.",
  "Görsel 20 MB sınırını aşıyor.": "Image exceeds the 20 MB limit.",
  "Görseller eklendi.": "Images added.",
  "Önce proje ayarlarını kaydet.": "Save project settings first.",
  "İşleme başlamadan önce metinleri kaydet.": "Save texts before starting an operation.",
  "Çalışıyor…": "Running…",
  "Başlıyor…": "Starting…",
  "İşlem başladı. Ayrıntılar aşağıda.": "Operation started. Details are below.",
  "Tamamlandı": "Completed",
  "Hata oluştu": "Failed",
  "İşlem tamamlandı. Durum bilgileri yenilendi.": "Operation completed. Readiness information has been refreshed.",
  "İşlem tamamlanamadı. Ayrıntıları aşağıdan kontrol et.": "Operation could not finish. Check the details below.",
  "Görev hazırlamadan önce metinleri kaydet.": "Save texts before preparing a task.",
  "Görev hazır. Kopyalayıp Flutter projen içindeki Claude Code veya Codex’e yapıştır.": "Task ready. Copy and paste into Claude Code or Codex in your Flutter project.",
  "Görev kopyalandı. Ajanına yapıştır; bitince sonuçları yükle.": "Task copied. Paste into your agent, then reload the results when it finishes.",
  "Metin seçildi. Ctrl/Cmd+C ile kopyalayabilirsin.": "Text selected. Copy with Ctrl/Cmd+C.",
  "Çeviri sonuçları yüklendi ve kontrol edildi.": "Translation results reloaded and checked.",
  "iOS uygulama kimliği (bundle ID)": "iOS app identifier (bundle ID)",
  "Apple e-posta adresi (isteğe bağlı)": "Apple email address (optional)",
  "Android uygulama kimliği (package name)": "Android app identifier (package name)",
  "Metinleri hangi dilde yazacaksın?": "Which language will you write in?",
  "Proje ayarları ve gerekli dosyalar hazır. Tamamlanan adımları durum ekranında görebilirsin.": "Project settings and helper files are ready. Check completed steps in the overview.",
  "Önce kimlik dosyasını seç.": "Select a credential file first.",
  "Dosya eklendi. Şimdi mağaza erişimini kontrol et.": "File added. Check store access next.",
  "iPhone ekran görüntüleri": "iPhone screenshots",
  "iPad ekran görüntüleri": "iPad screenshots",
  "Telefon ekran görüntüleri": "Phone screenshots",
  "7 inç tablet": "7-inch tablet",
  "10 inç tablet": "10-inch tablet",
  "TV ekran görüntüleri": "TV screenshots",
  "Wear OS ekran görüntüleri": "Wear OS screenshots",
  "Tanıtım görseli (feature graphic)": "Feature graphic",
  " · ": " · ",
  "✓ Tamam": "✓ Done",
  "İsteğe bağlı": "Optional",
  "Proje ayarları ve yardımcı dosyalar": "Project settings and helper files",
  "Dosyalar güncel. Yeniden kurulum yapmana gerek yok.": "Files are up to date. No setup needs repeating.",
  "Uygulama kimliği henüz girilmemiş. Kurulumdan tamamla.": "App identifier is missing. Complete it in Setup.",
  " yardımcı dosya eksik veya güncel değil.": " helper files are missing or outdated.",
  "Ayarları gör": "View settings",
  "Mağaza kimlik dosyası": "Store credential file",
  "Geçerli dosya bulundu. Yeniden indirmen veya eklemen gerekmiyor.": "A valid-format file was found. No need to download or import it again.",
  "Dosya okunuyor ama biçimi geçersiz. Doğru dosyayı seç.": "The file was read but its format is invalid. Select the correct file.",
  "Henüz eklenmemiş. Metin/çeviri hazırlarken bu adımı geçebilirsin.": "Not added yet. You can skip this step while preparing texts/translations.",
  "Bağlantıyı gör": "View connection",
  "Bağlantıyı kur": "Set up connection",
  "Mağaza erişimi": "Store access",
  "Bu oturumda kontrol edildi. Ayar/anahtar değişmedikçe yeniden kontrol gerekmez.": "Checked in this session. No need to repeat unless settings/key change.",
  "Henüz canlı kontrol yapılmadı. Dosya bulunması yetki verildiğini kanıtlamaz.": "No live check has run yet. Finding a file does not prove access was granted.",
  "Erişimi kontrol et": "Check access",
  "Yerel kaynak metin yok. Yeni içerik/çeviri hazırlayacaksan metinler adımına geç; mağaza metinlerini değiştirmeyeceksen bu adımı geçebilirsin.": "No local source texts exist. Open Texts for new content/translation; skip this step if you are keeping the current store texts.",
  "Metinleri aç": "Open texts",
  "Diğer diller": "Other languages",
  " alan boş. Çeviri görevi yalnızca boş alanları doldurur.": " empty fields. The translation task fills only empty fields.",
  "Eklenen dillerde boş çeviri alanı yok. Tekrar çeviri yapmana gerek yok.": "No missing translation fields in added languages. No need to translate again.",
  "Henüz hedef dil eklenmemiş. Tek dil kullanacaksan çeviri gerekmiyor.": "No target languages added yet. Translation is not needed if you use one language.",
  "Dilleri yönet": "Manage languages",
  " yerel görsel bulundu. Göndermeden önce kontrol edilir.": " local images found. They are checked before upload.",
  "Yeni görsel eklenmemiş. Mağazadakiler uygunsa bu adımı geç; mevcut görseller korunur.": "No new images added. Skip if your store images are suitable; existing images are preserved.",
  "Görselleri aç": "Open images",
  "Yükleme araçları": "Upload tools",
  " ve iOS araçları": " and iOS tools",
  " çalışıyor. Tekrar kurulum gerekmez.": " are working. No reinstall is needed.",
  "Henüz tam kontrol edilmedi veya eksik araç var. Metin hazırlamak için gerekmez.": "Not fully checked yet, or tools are missing. Not needed to prepare texts.",
  "Metin kontrolü": "Text validation",
  "Metinleri düzelt": "Fix texts",
  "Önce eksik proje ayarlarını tamamla. Var olan dosyalar korunur.": "Complete missing project settings first. Existing files are preserved.",
  "Kurulum dosyaları hazır. Yeni metin veya çeviri istiyorsan kaynak metinlerini yaz.": "Setup files are ready. Write source texts if you want new content or translations.",
  "Kaynak metinlerin hazır. Sıradaki iş: diğer dillerdeki boş alanları doldur.": "Source texts are ready. Next: fill the missing fields in other languages.",
  "İçerik hazırlığı hazır. Göndereceksen mağaza bağlantısını tamamla.": "Content preparation is ready. Complete the store connection if you want to upload.",
  "Yükleme için yerel dosyalar hazır. Mağaza erişimini kontrol edip yükleme planına geçebilirsin.": "Local upload files are ready. Check store access and continue to the upload plan.",
  "Çeviriye git": "Go to translation",
  "Göndermeye geç": "Continue to upload",
  "Proje ayarları ve yardımcı dosyalar hazır. Tekrar kaydetmen gerekmez.": "Project settings and helper files are ready. No need to save again.",
  "Eksik ayarları tamamlayıp kaydet. Eski dosyalar güncellenirken yedeklenir.": "Complete missing settings and save. Changed helper files receive backups.",
  "✓ Mağaza erişimi bu oturumda doğrulandı. Başka işlem gerekmiyor.": "✓ Store access verified in this session. No further action is needed.",
  "✓ Kimlik dosyası bulundu; yeniden ekleme gerekmez. Erişim henüz kontrol edilmedi.": "✓ Credential file found; no need to import again. Access has not been checked yet.",
  "Kimlik dosyası bulundu. Apple Key ID ayarını tamamla.": "Credential file found. Complete the Apple Key ID setting.",
  "Kimlik dosyası geçersiz. Aşağıdan doğru dosyayı seç.": "Credential file is invalid. Select the correct file below.",
  "Kimlik dosyası bulunamadı. İçerik hazırlamak için bu adımı geçebilirsin.": "Credential file not found. You can skip this while preparing content.",
  "✓ Erişim doğrulandı": "✓ Access verified",
  "henüz kontrol edilmedi": "not checked yet",
  "hazır": "ready",
  "eksik / çalışmıyor": "missing / not working",
  "Henüz kontrol edilmedi. Metin ve çeviri için gerekmez; göndermeden önce kontrol edebilirsin.": "Not checked yet. Not needed for texts or translation; check before uploading.",
  "✓ Mağaza araçları hazır": "✓ Store tools are ready",
  "Android imzalama ayar dosyası bulundu; Gradle ve keystore ile build doğrulaması gerekir.": "Android signing settings file found; a build must verify Gradle and the keystore.",
  "iOS export ayarları bulundu; sertifika/provisioning bu kontrolde doğrulanmadı.": "iOS export settings found; certificates/provisioning were not verified by this check.",
  "Yerel imzalama kanıtı yok; yalnızca yeni build oluşturacaksan kontrol et.": "No local signing evidence found; check only if you will create a new build.",
  " · Kaynak dil: ": " · Source language: ",
  "Bu mağazada desteklenmiyor": "Not supported by this store",
  ". Çeviri diğer dillere bu metinlerden yapılır.": ". These texts are used to translate other languages.",
  "Kaynak dil bu mağazada desteklenmiyor. Kurulumda değiştir.": "Source language is not supported by this store. Change it in Setup.",
  "Önce Metinler adımındaki biçim/uzunluk hatalarını düzelt.": "Fix text format/length issues in the Texts step first.",
  "Önce Metinler adımında kaynak dili doldur.": "Fill the source language in the Texts step first.",
  "Kaynak metin hazır. Çevirmek istediğin ilk dili aşağıdan ekle.": "Source texts are ready. Add your first target language below.",
  " hedef dil · ": " target languages · ",
  " alan eksik. Görev bunları dolduracak.": " missing fields. The task will fill them.",
  "✓ Eklenen dillerde boş çeviri alanı yok. Bu adımı geçebilirsin.": "✓ No missing translation fields in added languages. You can skip this step.",
  "Göndermeden önce ": "Before uploading, complete the ",
  " bağlantısını Kurulum adımından tamamla. Plan kontrolü için kimlik dosyası gerekmez.": " connection in Setup. No credential file is needed to check a plan.",
  "✓ Seçilen mağazaların erişimi doğrulandı. Önce planı kontrol et, sonra gönder.": "✓ Access to the selected stores is verified. Check the plan first, then upload.",
  "Yerel kimlik dosyaları hazır. Göndermeden önce Kurulum adımından mağaza erişimini kontrol etmeni öneririz.": "Local credential files are ready. We recommend checking store access in Setup before uploading.",
  "Yeni build için Flutter, Android SDK veya Xcode ve release imzalama gerekir. Kurulumdaki araç/imzalama kontrolünü kullan. Hazır build göndereceksen yeniden build oluşturman gerekmez.": "New builds need Flutter, Android SDK or Xcode, and release signing. Use the tools/signing checks in Setup. No need to rebuild if you will upload an existing build.",
  "Mağaza seçimini değiştirmeden önce düzenlemelerini kaydet.": "Save your edits before changing the store selection.",
  "Önce düzenlemelerini kaydet.": "Save your edits first.",
  "Dosyalar yeniden kontrol edildi. Hazır işleri tekrar yapmana gerek yok.": "Files checked again. No need to repeat completed steps.",
  "Kurulumda bu mağazanın desteklediği kaynak dili seç.": "Select a source language supported by this store in Setup.",
  "Diğer mağazadaki ortak kaynak alanları alındı. Mevcut dolu alanlar korundu; metin sınırlarını kontrol et.": "Common source fields were copied from the other store. Existing values were preserved; check field limits.",
  "Yardımcı dosyalar güncellendi. Mevcut içerik ve ayarlar korundu.": "Helper files updated. Existing content and settings were preserved.",
  "Projen kontrol edildi. Durum ekranından eksik adıma devam et.": "Project checked. Continue to the next step in the overview.",
  "torchinlane.yaml okunamıyor. Önce yapılandırma dosyasını düzeltin.": "torchinlane.yaml could not be read. Fix the configuration file first.",
  "Bir içerik dosyası okunamıyor. JSON biçimini ve dil kodunu kontrol edin.": "A content file could not be read. Check its JSON format and locale code.",
  "Anahtar kelimeler": "Keywords",
  "Eksik": "Missing",
  " karakter": " characters",
  "tr veya en": "tr or en",
  "Uygulama ikonu": "App icon",
  "Anahtar bulundu; Apple Key ID eksik. Ayarlardan tamamla.": "Key found; Apple Key ID is missing. Complete it in settings.",
  "Kontrol edilmedi": "Not checked",
  "Kaynak metinler": "Source texts",
  "Kaynak dil: ": "Source language: ",
  ". Metinler bulundu; uygunlarsa yeniden yazmana gerek yok.": ". Texts found; no need to rewrite if they are suitable.",
  " hedef dilde ": " target languages have ",
  "Kuruluma git": "Go to setup",
  "Kaynak metinlere git": "Go to source texts",
  "Kaynak dilin ": "Your source language is ",
  " ve ": " and ",
  "Arayüz dili": "Interface language",
  "Türkçe": "Turkish",
  "İngilizce": "English",
  "Henüz işlem başlatılmadı.": "No operation started yet."
};
const uiLanguageKey='torchinlane:ui-language';
let uiLanguage='tr',savedUILanguage=null;
try{const saved=localStorage.getItem(uiLanguageKey);savedUILanguage=['tr','en'].includes(saved)?saved:null;uiLanguage=savedUILanguage|| (navigator.language.toLowerCase().startsWith('tr')?'tr':'en');}catch(e){uiLanguage=navigator.language.toLowerCase().startsWith('tr')?'tr':'en';}
const originalMessages=new Map(Object.entries(uiMessages).map(([tr,en])=>[en,tr]));
function messageSource(value){return typeof value==='string'?(originalMessages.get(value)||value):value;}
function t(value){if(typeof value!=='string')return value;const source=messageSource(value);return uiLanguage==='en'?(uiMessages[source]||source):source;}
const uiRichMessages={
  translationTask:{tr:'<strong>Çeviri görevini hazırla</strong> ve <strong>Görevi kopyala</strong> düğmelerine bas.',en:'Click <strong>Prepare translation task</strong>, then <strong>Copy task</strong>.'},
  translationResults:{tr:'Buraya dön ve <strong>Sonuçları yükle ve kontrol et</strong> düğmesine bas.',en:'Return here and click <strong>Reload and check results</strong>.'}
};
function formatMessage(source,values){return t(source).replace(/\{(\w+)\}/g,(_,key)=>String(values[key]??'{'+key+'}'));}
const staticBindings=[];
function bindStaticUI(){const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let node;while((node=walker.nextNode())){const parent=node.parentElement;if(!parent||parent.closest('script,style,textarea,[data-ui-fixed],[data-ui-rich]')||parent.closest('pre:not(#logs)'))continue;const text=node.data.trim();if(Object.hasOwn(uiMessages,text)){staticBindings.push({node,source:text,prefix:node.data.match(/^\s*/)[0],suffix:node.data.match(/\s*$/)[0]});}}document.querySelectorAll('[placeholder]').forEach(element=>{if(Object.hasOwn(uiMessages,element.placeholder))element.dataset.uiPlaceholder=element.placeholder;});}
function applyStaticUI(){document.documentElement.lang=uiLanguage;document.querySelectorAll('[data-ui-rich]').forEach(element=>element.innerHTML=uiRichMessages[element.dataset.uiRich][uiLanguage]);document.getElementById('uiLanguage').value=uiLanguage;for(const b of staticBindings){if(b.node.isConnected)b.node.data=b.prefix+t(b.source)+b.suffix;}document.querySelectorAll('[data-ui-placeholder]').forEach(element=>element.placeholder=t(element.dataset.uiPlaceholder));document.querySelectorAll('[data-ui-text]').forEach(element=>element.textContent=t(element.dataset.uiText));}

''';
