/// Embedded assets keep the globally activated Dart CLI self-contained.
const studioHtml = r'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Torchinlane Studio</title><style>
:root{color-scheme:dark;--bg:#10131b;--panel:#1a2030;--line:#30394f;--muted:#aeb9cd;--accent:#ffad64}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:#eef2fa;font:15px system-ui,sans-serif}header{padding:24px 5%;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center}h1{font-size:24px;margin:0}small,.hint{color:var(--muted)}nav{padding:18px 5%;display:flex;gap:10px;flex-wrap:wrap}button{border:1px solid var(--line);background:#253049;color:#eef2fa;padding:10px 16px;border-radius:8px;cursor:pointer;font:inherit}button:hover,button.active{border-color:var(--accent)}button.primary{background:var(--accent);color:#21160b;font-weight:650}button:disabled{opacity:.5;cursor:wait}main{max-width:1200px;margin:auto;padding:12px 24px 70px}.card{background:var(--panel);padding:24px;border-radius:14px;border:1px solid var(--line);margin:0 0 20px}h2{font-size:19px;margin-top:0}h3{font-size:16px}label{display:block;color:var(--muted);margin:16px 0 7px}input,select,textarea{background:#101725;border:1px solid #3b4862;color:#eef2fa;border-radius:7px;padding:10px;width:100%;font:inherit}textarea{min-height:95px;resize:vertical}.row{display:flex;gap:16px;flex-wrap:wrap;align-items:flex-end}.row>div{flex:1;min-width:150px}.row.buttons{margin-top:20px;align-items:center}input[type=checkbox]{width:auto}input[type=file]{max-width:450px}a{color:#ffbf89}.hidden{display:none!important}.status{padding:12px 5%;background:#202b3c;white-space:pre-wrap;overflow-wrap:anywhere}.counter{font-size:12px;color:var(--muted);text-align:right}.counter.invalid{color:#ff8c8c}.gallery{display:flex;gap:12px;flex-wrap:wrap}.image{width:150px;background:#111827;padding:8px;border-radius:8px}.image img{width:100%;height:190px;object-fit:contain}.image button{padding:5px;margin:3px;font-size:12px}.image small{display:block;overflow-wrap:anywhere}pre{background:#0b1019;padding:16px;max-height:400px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:0 20px}.check{display:flex;align-items:center;gap:8px}footer{color:var(--muted);margin-top:20px}#remoteDiff{max-height:160px;overflow:auto}.badge{font-size:12px;padding:6px 10px;border-radius:20px;background:#303c55}
</style></head><body><header><div><h1>🔥 Torchinlane Studio</h1><small>Local workspace · Store content & release automation</small></div><span class="badge" id="appName">Flutter project</span></header>
<nav><button class="active" data-tab="content">Store content</button><button data-tab="release">Upload & deploy</button><button data-tab="setup">Setup & credentials</button></nav>
<div class="status" id="status" role="status">Loading workspace…</div><main>
<section id="content"><div class="card"><h2>Localized store content</h2><p class="hint">Each store has its own languages and field limits. Save changes before translating or uploading. Empty fields preserve existing store text.</p>
<div class="row"><div><label for="platform">Store</label><select id="platform"><option value="ios">App Store</option><option value="android">Google Play</option></select></div><div><label for="locale">Locale</label><select id="locale"></select></div><div><label for="addLocale">Add locale</label><select id="addLocale"></select></div><button id="addLocaleButton">Add</button><button id="allLocales">Add all supported locales</button></div>
<div id="editor"></div><div class="row buttons"><button class="primary" id="save">Save texts</button><button id="validate">Validate this store</button></div></div>
<div class="card"><h2>Translation</h2><p class="hint">Prepare a task for Claude Code or Codex in this Flutter project. No translation API key is needed. Save source texts and add target locales first. Paste the task into your agent, then reload and validate its changes.</p><div class="row"><div><label for="from">Source locale</label><select id="from"></select></div><label class="check"><input type="checkbox" id="overwrite">Overwrite existing translations</label><button class="primary" id="prepareTask">Prepare agent task</button><button id="translate">Translate via optional API</button></div><p class="hint">API translation is optional, requires ANTHROPIC_API_KEY and may incur separate charges.</p><div id="taskPanel" class="hidden"><label for="agentTask">Task to paste into your coding agent</label><textarea id="agentTask" readonly rows="14"></textarea><div class="row buttons"><button id="copyTask">Copy task</button><button id="reloadTranslations">Reload agent changes</button></div></div></div>
<div class="card"><h2>Store images</h2><p class="hint">Import ready-made PNG/JPEG assets for the selected locale. Dimensions and transparency are checked. Arrow buttons set upload order. Capture does not automatically translate your app or artwork.</p><div class="row"><div><label for="group">Device / asset type</label><select id="group"></select></div><div><label for="images">Import images</label><input type="file" id="images" accept="image/png,image/jpeg" multiple></div></div><div class="gallery" id="gallery"></div></div></section>
<section id="release" class="hidden"><div class="card"><h2>Upload store content</h2><p class="hint">Uploads saved content without a build. This does not submit an Apple review or start a Google production rollout. Google notes require a version code already present on the selected track.</p>
<div class="row"><div><label for="uploadPlatform">Platforms</label><select id="uploadPlatform"><option value="ios,android">Both</option><option value="ios">App Store</option><option value="android">Google Play</option></select></div><div><label for="scope">Content</label><select id="scope"><option value="all">All content</option><option value="metadata">Texts only</option><option value="images">Images only</option><option value="notes">Release notes only</option></select></div><div><label for="track">Google track</label><select id="track"><option>internal</option><option>alpha</option><option>beta</option><option>production</option></select></div></div>
<div class="row"><div><label for="versionCode">Google version code</label><input id="versionCode" type="number" min="1" placeholder="e.g. 42"></div><div><label for="appVersion">Apple editable version</label><input id="appVersion" placeholder="e.g. 1.2.0"></div></div>
<label class="check"><input id="replaceImages" type="checkbox">Replace existing Apple screenshots in supplied locales (all device sets)</label><p class="hint">Google replaces supplied image groups. Omitted groups are preserved. Apple adds images by default; enable replacement when synchronizing a set.</p>
<div class="row buttons"><button id="export">Export Fastlane files</button><button id="dryRun">Validate upload plan</button><button class="primary" id="push">Upload saved content</button><button id="pull">Compare remote texts</button><button id="pullApply">Import remote texts with backups</button></div></div>
<div class="card"><h2>Build & deploy</h2><p class="hint">Builds use Flutter and the local native toolchains. iOS builds require macOS/Xcode and configured signing. Google releases remain drafts here. For rollout automation use CLI --release-status completed explicitly.</p><div class="row"><div><label for="target">Target</label><select id="target"><option value="internal">TestFlight / Play internal draft</option><option value="production">App Store / Play production draft</option></select></div><label class="check"><input id="uploadOnly" type="checkbox">Upload existing build</label><label class="check"><input id="withStore" type="checkbox" checked>Include store content</label></div><div class="row buttons"><button id="deployPlan">Preview commands</button><button class="primary" id="deploy">Build & upload</button></div></div></section>
<section id="setup" class="hidden"><div class="card"><h2>Project configuration</h2><p class="hint">Setup generates Fastlane files and protects credential paths in .gitignore. Existing configuration and content are preserved; changed generated files receive .bak backups. Complete only the store credentials you will use.</p><form id="setupForm"><div class="grid" id="setupFields"></div><div class="row buttons"><button class="primary" type="submit">Save configuration & sync Fastlane</button><button type="button" id="tools">Install / repair Fastlane & CocoaPods</button></div></form></div>
<div class="card"><h2>Apple connection</h2><p><a href="https://appstoreconnect.apple.com/access/integrations/api" target="_blank" rel="noreferrer">Open App Store Connect API keys</a></p><ol class="hint"><li>Account Holder enables API access; Account Holder/Admin generates a team key with the required app management role.</li><li>Download the .p8 once. Enter Key ID and Issuer ID above and save.</li><li>Import the file below, then verify app access. Signing certificates/profiles are separate.</li></ol><label for="appleKey">Apple .p8</label><input id="appleKey" type="file" accept=".p8"><label for="appleProfile">Reusable profile (optional)</label><input id="appleProfile" placeholder="company-apple"><button id="importApple">Import Apple key</button></div>
<div class="card"><h2>Google connection</h2><p><a href="https://console.cloud.google.com/iam-admin/serviceaccounts" target="_blank" rel="noreferrer">Google Cloud service accounts</a> · <a href="https://play.google.com/console" target="_blank" rel="noreferrer">Play Console</a></p><ol class="hint"><li>Enable Google Play Developer API and create a service account (or use CLI credentials bootstrap-google).</li><li>In Play Console, invite the service account email and grant access to the app and required releases.</li><li>Import JSON, or configure GOOGLE_APPLICATION_CREDENTIALS for WIF/OAuth. New apps need their first build uploaded through Play Console.</li></ol><label for="googleKey">Google credential JSON</label><input id="googleKey" type="file" accept=".json"><label for="googleProfile">Reusable profile (optional)</label><input id="googleProfile" placeholder="company-google"><button id="importGoogle">Import Google credentials</button><p class="hint">For keyless GitHub CI: <code>torchinlane credentials bootstrap-google --project-id YOUR_PROJECT --repository OWNER/REPO</code>. See doc/automation.md for workflow and initial permissions.</p></div><div class="card"><h2>Check connection</h2><p class="hint">Checks API authentication and access to the configured app. Google creates and discards an uncommitted edit. No release is uploaded.</p><div class="row buttons"><button id="verifyApple">Verify Apple</button><button id="verifyGoogle">Verify Google</button></div></div></section>
<div class="card"><h2>Activity</h2><span id="jobStatus">Idle</span><pre id="logs" aria-live="polite">No operation started.</pre></div><footer>Credentials stay on this computer. Agent tasks stay local until you share them with your coding agent. Optional API translation sends selected text to Anthropic. Store uploads send supplied content to Apple/Google.</footer></main>
<script>
'use strict';
const token=location.hash.slice(1);history.replaceState(null,'',location.pathname);const $=id=>document.getElementById(id);
let state={},current={fields:{},images:{}},dirty=false,polling=false,loadedPlatform='',loadedLocale='';
const labels={name:'App name',subtitle:'Subtitle',description:'Description',keywords:'Keywords',promotional_text:'Promotional text',support_url:'Support URL',marketing_url:'Marketing URL',privacy_url:'Privacy policy URL',release_notes:'Release notes',title:'App name',short_description:'Short description',full_description:'Full description',video:'YouTube video URL'};
function status(s){$('status').textContent=s;}
async function api(path,data){const res=await fetch(path,{method:data===undefined?'GET':'POST',headers:{'X-Torchinlane-Token':token,'Content-Type':'application/json'},...(data===undefined?{}:{body:JSON.stringify(data)})});const result=await res.json();if(!res.ok)throw Error(result.error||'Request failed');return result;}
function safely(fn){return async event=>{try{await fn(event);}catch(e){status(e.message);}};}
function options(select,values,selected){select.replaceChildren();for(const value of values){const option=document.createElement('option');option.value=value;option.textContent=value;select.append(option);}if(values.includes(selected))select.value=selected;}
async function refresh(){state=await api('/api/state');$('appName').textContent=state.appName;const platform=$('platform').value;options($('locale'),state.locales[platform],$('locale').value);options($('addLocale'),state.available[platform]);options($('from'),state.locales[platform],state.locales[platform].find(l=>l==='en-US')||state.locales[platform][0]);options($('group'),state.groups[platform],$('group').value);$('translate').disabled=!state.aiAvailable;renderSetup();await loadContent();if(!state.configured){tab('setup');status('Complete project setup to connect stores. You can prepare content first.');}else status('Workspace ready.');}
function tab(name){for(const section of ['content','release','setup'])$(section).classList.toggle('hidden',section!==name);document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));}
for(const button of document.querySelectorAll('[data-tab]'))button.onclick=()=>tab(button.dataset.tab);
async function loadContent(){const platform=$('platform').value,locale=$('locale').value;$('editor').replaceChildren();$('gallery').replaceChildren();if(!locale)return;loadedPlatform=platform;loadedLocale=locale;current=await api('/api/content?'+new URLSearchParams({platform,locale}));for(const [key,limit]of Object.entries(state.fields[platform])){const label=document.createElement('label');label.htmlFor='field_'+key;label.textContent=labels[key]||key;const input=document.createElement(limit===0||['name','title','subtitle','keywords'].includes(key)?'input':'textarea');input.id='field_'+key;input.dataset.field=key;input.value=current.fields[key]||'';const counter=document.createElement('div');counter.className='counter';const update=()=>{const isBytes=platform==='ios'&&key==='keywords';const length=isBytes?new TextEncoder().encode(input.value).length:Array.from(input.value).length;counter.textContent=limit?length+' / '+limit+(isBytes?' UTF-8 bytes':' characters'):'URL';counter.classList.toggle('invalid',limit>0&&length>limit);};input.oninput=()=>{dirty=true;update();};update();$('editor').append(label,input,counter);}dirty=false;gallery();}
function gallery(){const platform=$('platform').value,group=$('group').value,paths=current.images[group]||[];$('gallery').replaceChildren();paths.forEach((path,index)=>{const card=document.createElement('div');card.className='image';const image=document.createElement('img');image.alt=path.split('/').pop();image.src='/asset?'+new URLSearchParams({path,token});const name=document.createElement('small');name.textContent=image.alt;card.append(image,name);for(const[caption,delta]of [['←',-1],['→',1]]){const b=document.createElement('button');b.textContent=caption;b.disabled=index+delta<0||index+delta>=paths.length;b.onclick=safely(async()=>{const order=paths.slice();[order[index],order[index+delta]]=[order[index+delta],order[index]];await api('/api/reorder',{platform,locale:$('locale').value,group,paths:order});await reloadImages();});card.append(b);}const remove=document.createElement('button');remove.textContent='Delete local';remove.onclick=safely(async()=>{await api('/api/delete-image',{path});await reloadImages();});card.append(remove);$('gallery').append(card);});}
async function reloadImages(){const data=await api('/api/content?'+new URLSearchParams({platform:$('platform').value,locale:$('locale').value}));current.images=data.images;gallery();}
$('platform').onchange=safely(async()=>{if(dirty){$('platform').value=loadedPlatform;throw Error('Save current edits before switching store.');}await refresh();});
$('locale').onchange=safely(async()=>{if(dirty){$('locale').value=loadedLocale;throw Error('Save current edits before switching locale.');}await loadContent();});
$('group').onchange=gallery;
$('save').onclick=safely(async()=>{const fields={};document.querySelectorAll('[data-field]').forEach(input=>fields[input.dataset.field]=input.value);await api('/api/save',{platform:$('platform').value,locale:$('locale').value,fields});dirty=false;status('Texts saved locally.');});
$('addLocaleButton').onclick=safely(async()=>{if(dirty)throw Error('Save current text edits first.');await api('/api/init',{platform:$('platform').value,locales:[$('addLocale').value]});await refresh();});
$('allLocales').onclick=safely(async()=>{if(dirty)throw Error('Save current text edits first.');await api('/api/init',{platform:$('platform').value,locales:state.available[$('platform').value]});await refresh();});
$('validate').onclick=safely(async()=>{const data=await api('/api/validate',{platform:$('platform').value});status(data.errors.length?data.errors.join('\n'):'Saved store content passed validation.');});
$('images').onchange=safely(async()=>{for(const file of $('images').files){const bytes=new Uint8Array(await file.arrayBuffer());if(bytes.length>20*1024*1024)throw Error('Image exceeds 20 MB');let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));await api('/api/image',{platform:$('platform').value,locale:$('locale').value,group:$('group').value,name:file.name,bytes:btoa(binary)});}await reloadImages();$('images').value='';status('Images imported.');});
function jobData(){return{platform:$('uploadPlatform').value,scope:$('scope').value,track:$('track').value,versionCode:$('versionCode').value,appVersion:$('appVersion').value,replaceImages:$('replaceImages').checked};}
function setBusy(value){document.querySelectorAll('main button,main input,main textarea,main select').forEach(e=>{if(value){e.dataset.studioDisabled=String(e.disabled);e.disabled=true;}else if('studioDisabled' in e.dataset){e.disabled=e.dataset.studioDisabled==='true';delete e.dataset.studioDisabled;}});if(!value)$('translate').disabled=!state.aiAvailable;}
async function startJob(data){if(dirty)throw Error('Save text edits before starting an operation.');await api('/api/job',data);setBusy(true);status('Operation started. Activity log below.');if(!polling)poll();}
async function poll(){polling=true;try{const job=await api('/api/job');$('logs').textContent=job.logs.join('\n')||'Starting…';$('jobStatus').textContent=job.running?'Running…':job.exitCode===null?'Idle':job.exitCode===0?'Completed':'Failed';if(job.running)setTimeout(poll,1000);else{polling=false;await refresh();setBusy(false);status(job.exitCode===0?'Operation completed.':'Operation failed; see Activity.');}}catch(e){polling=false;setBusy(false);status(e.message);}}
$('export').onclick=safely(()=>startJob({...jobData(),action:'export'}));$('push').onclick=safely(()=>startJob({...jobData(),action:'push'}));$('dryRun').onclick=safely(()=>startJob({...jobData(),action:'push',dryRun:true}));$('pull').onclick=safely(()=>startJob({...jobData(),action:'pull'}));$('pullApply').onclick=safely(()=>startJob({...jobData(),action:'pull',apply:true}));
$('prepareTask').onclick=safely(async()=>{if(dirty)throw Error('Save text edits before preparing a task.');const data=await api('/api/translation-task',{platform:$('platform').value,from:$('from').value,overwrite:$('overwrite').checked});$('agentTask').value=data.prompt;$('taskPanel').classList.remove('hidden');status('Task ready. Paste into Claude Code or Codex working in this Flutter project.');});
$('copyTask').onclick=safely(async()=>{try{await navigator.clipboard.writeText($('agentTask').value);status('Agent task copied.');}catch(e){$('agentTask').focus();$('agentTask').select();status('Clipboard unavailable. Task selected; copy it manually.');}});
$('reloadTranslations').onclick=safely(async()=>{if(dirty)throw Error('Save current text edits first.');await refresh();const data=await api('/api/validate',{platform:$('platform').value});status(data.errors.length?data.errors.join('\n'):'Agent changes reloaded and validated.');});
$('translate').onclick=safely(()=>startJob({action:'translate',platform:$('platform').value,from:$('from').value,overwrite:$('overwrite').checked}));
function deploy(dryRun){return startJob({action:'deploy',platform:$('uploadPlatform').value,target:$('target').value,uploadOnly:$('uploadOnly').checked,withStore:$('withStore').checked,dryRun});}
$('deploy').onclick=safely(()=>deploy(false));$('deployPlan').onclick=safely(()=>deploy(true));
const setupLabels={app_name:'App name',bundle_id:'iOS bundle identifier',team_id:'Apple Developer Team ID',apple_id:'Apple ID email (optional for API)',asc_key_id:'Apple API Key ID',asc_issuer_id:'Apple API Issuer ID',package_name:'Android package name',source_locale:'Source locale'};
function renderSetup(){if($('setupFields').children.length)return;for(const[key,labelText]of Object.entries(setupLabels)){const div=document.createElement('div'),label=document.createElement('label'),input=document.createElement('input');label.textContent=labelText;label.htmlFor='setup_'+key;input.id='setup_'+key;input.name=key;input.value=state.config[key]||({'source_locale':'en','app_name':state.appName}[key]||'');div.append(label,input);$('setupFields').append(div);}}
$('setupForm').onsubmit=safely(async event=>{event.preventDefault();if(dirty)throw Error('Save current text edits first.');const values=Object.fromEntries(new FormData($('setupForm')));await api('/api/setup',values);await refresh();status('Project configuration and Fastlane files saved. Import credentials and verify connections.');});
async function importKey(platform,fileId,profileId){const file=$(fileId).files[0];if(!file)throw Error('Select a credential file first.');const profile=$(profileId).value.trim();await api('/api/credential',{platform,contents:await file.text(),...(profile?{profile}:{})});$(fileId).value='';status('Credential imported locally. Verify connection next.');}
$('importApple').onclick=safely(()=>importKey('ios','appleKey','appleProfile'));$('importGoogle').onclick=safely(()=>importKey('android','googleKey','googleProfile'));$('verifyApple').onclick=safely(()=>startJob({action:'verify',platform:'ios'}));$('verifyGoogle').onclick=safely(()=>startJob({action:'verify',platform:'android'}));$('tools').onclick=safely(()=>startJob({action:'tools',platform:$('uploadPlatform').value}));
refresh().catch(e=>status(e.message));
</script></body></html>''';
